# SPDX-FileCopyrightText: 2024 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

# This file describes the licenses of the files that are packaged in the resulting NuGet package.
# Note that these are not necessarily all the licenses used by the project; only those related to the packaged files.

metadata_sources = [
    { type = "nuget", include = "DotNetLicenses.sln" },
    { type = "reuse", root = ".", patterns_covered = [
        { type = "nuget" },
        { type = "msbuild", include = "DotNetLicenses.sln" }
    ] }
]

# REUSE-IgnoreStart
metadata_overrides = [
    { id = "GitignoreParserNet", version = "0.2.0.12", spdx = "Apache-2.0", copyright = [
        "Copyright (c) 2021 Gyuirgy",
        "Copyright 2014 codemix ltd."
    ] }
]
# REUSE-IgnoreEnd

lock_file = ".dotnet-licenses.lock.toml"
packaged_files = [
    { type = "zip", path = "DotNetLicenses/bin/Release/FVNever.DotNetLicenses.0.0.0.nupkg" }
]
