# SPDX-FileCopyrightText: 2024 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

# This file describes the licenses of the files that are packaged in the resulting NuGet package.
# Note that these are not necessarily all the licenses used by the project; only those related to the packaged files.

metadata_sources = [
    { type = "nuget", include = "DotNetLicenses/DotNetLicenses.fsproj" },
    { type = "license", spdx = "MIT", copyright = "2024 Friedrich von Never <friedrich@fornever.me>", patterns_covered = [
        { type = "nuget" },
        { type = "msbuild", include = "DotNetLicenses/DotNetLicenses.fsproj" }
    ] },
    { type = "reuse", root = "." }
]
lock_file = ".dotnet-licenses.lock.toml"
packaged_files = [
    { type = "zip", path = "DotNetLicenses/bin/Release/FVNever.DotNetLicenses.0.0.0.nupkg" }
]
