[["tools/net8.0/any/FSharp.Core.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/JetBrains.Annotations.dll"]]
source_id = "JetBrains.Annotations"
source_version = "2023.3.0"
spdx = "MIT"
[["tools/net8.0/any/JetBrains.Lifetimes.dll"]]
source_id = "JetBrains.Lifetimes"
source_version = "2024.1.1"
spdx = "Apache-2.0"
copyright = "Copyright © JetBrains 2024"
[["tools/net8.0/any/MedallionShell.dll"]]
source_id = "MedallionShell"
source_version = "1.6.2"
spdx = "MIT"
copyright = "Copyright © 2017 Michael Adelson"
[["tools/net8.0/any/Microsoft.Extensions.FileSystemGlobbing.dll"]]
source_id = "Microsoft.Extensions.FileSystemGlobbing"
source_version = "8.0.0"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/Tomlyn.dll"]]
source_id = "Tomlyn"
source_version = "0.17.0"
spdx = "BSD-2-Clause"
copyright = "Alexandre Mutel"
[["tools/net8.0/any/cs/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/de/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/es/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/fr/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/it/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/ja/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/ko/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/pl/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/pt-BR/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/ru/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/tr/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/zh-Hans/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
[["tools/net8.0/any/zh-Hant/FSharp.Core.resources.dll"]]
source_id = "FSharp.Core"
source_version = "8.0.200"
spdx = "MIT"
copyright = "© Microsoft Corporation. All rights reserved."
