# SPDX-FileCopyrightText: 2024 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

# This file describes the licenses of the files that are packaged in the resulting NuGet package.
# Note that these are not necessarily all the licenses used by the project; only those related to the packaged files.

inputs = [
    "DotNetLicenses/DotNetLicenses.fsproj"
]
lock_file = ".dotnet-licenses.lock.toml"
